version: "3"
services:
  uapi-build:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./build:/build
      - ./uAPI:/uAPI
  uapi-test:
    build:
      context: .
      dockerfile: tests/testserver/Dockerfile
